############################
## Author
############################

author:
  name: GionaBolzer
  image: author1.jpg
  greeting: "Sales & Marketing Coordinator"
#  icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/GionaBolzer/
  # - link: https://github.com/GionaBolzer/blog#
  # - website: 
  # - x-twitter: 
  # - mastodon: 
  - linkedin:  https://www.linkedin.com/in/giona-bolzer-49114534a
  - instagram: https://www.instagram.com/gionabolzer/
  # - reddit: 
  # - telegram: 
  # - whatsapp: 
  # - signal: 
  # - codepen: 
  # - dev: 
  - email: mailto:gionabolzer2@gmail.com
  # - discord: 
  # - orcid: 
  # - slack: 
  # - stack-overflow: 
  # - twitch: 
  # - patreon: 
  # - soundcloud: 
  # - dribbble: 
  # - stack-exchange: 
  # - tiktok: 
  # - youtube: 
  # - keybase: 
  # - flickr: 
  # - tumblr: 
  # - kickstarter: 
  # - snapchat:
  # - bluesky: 
  # - bitbucket: 
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  # - pinterest: 
  # - strava: 
  # - untappd: 
  # - skype: 
  # - medium: 
  # - foursquare: 
  # - apple: 
  # - amazon:
  # - google:
  # - paypal:
  # - windows:

###############################
## OpenGraph & Twitter Cards
###############################

title: blog
description: ""
images:
  - author1.jpg
